import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// // import ivm from '../lib/isolated-vm';
// const ivm = require('../lib/isolated-vm')
// import { Builder } from '@builder.io/react';
 
// const isolate = new ivm.Isolate({ memoryLimit: 128 });
// const context = isolate.createContextSync();
// Builder.setServerContext(context);

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
